<?php

include_once "Point2D.php";

class Point3D extends Point2D
{
    private $z;

    public function __construct($x, $y, $z)
    {
        parent::__construct($x, $y);

        $this->z = $z;
    }

    public function setZ($z)
    {
        $this->z = $z;
    }

    public function getZ()
    {
        return $this->z;
    }

    public function setXYZ($x, $y, $z)
    {
        parent::setXY($x, $y); // TODO: Change the autogenerated stub
        $this->z = $z;

    }

   public function getXYZ()
   {
//       return array_push(parent::getXY(),$this->z); // TODO: Change the autogenerated stub
    return array($this->getX(),$this->getY(),$this->z);
   }

    public function toString()
    {
        return parent::toString() . " z= " . $this->z; // TODO: Change the autogenerated stub

    }
}