<?php

include_once "Point.php";

class MoveablePoint extends Point2D
{
    private $xSpeed;
    private $ySpeed;

    function __construct($x, $y, $xSpeed, $ySpeed)
    {
        parent::__construct($x, $y);
        $this->xSpeed = $xSpeed;
        $this->ySpeed = $ySpeed;
    }

    function setXSpeed($xSpeed)
    {
        $this->xSpeed = $xSpeed;
    }

    function setYSpeed($ySpeed)
    {
        $this->ySpeed = $ySpeed;
    }

    function getXSpeed()
    {
        return $this->xSpeed;
    }

    function getYSpeed()
    {
        return $this->ySpeed;
    }

    public function set_Speed($xspeed, $yspeed)
    {
        $this->xSpeed = $xspeed;
        $this->ySpeed = $yspeed;
    }

    public function get_Speed()
    {
        return $arr = array($this->xSpeed, $this->ySpeed);
    }

    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo "<br>";
        echo "XSpeed is: " . $this->getXSpeed();
        echo "<br>";
        echo "YSpeed is: " . $this->getYSpeed();
    }

    public function move()
    {
        echo "MovablePoint X is: " . $this->x+= $this->xSpeed;
        echo "<br>";
        echo "MovablePoint Y is: " . $this->y+= $this->ySpeed;
    }
}

