<?php
include_once "Rectangle.php";
include_once "interfaceResizeable.php";
class Square extends Rectangle
{
    public function __construct($name, $height, $width)
    {
        parent::__construct($name, $height, $width);
    }
    public function get_Area()
    {
        return $this->height * $this->height;
    }
    public function resize($value)
    {
        parent::resize($value); // TODO: Change the autogenerated stub
    }
}